### ISSUE TITLE
two INCLUDES redeclare %localdata

### ISSUE THREAD

**Issue by dagurval** [raku-community-modules/Template6#2]
%localdata gets declared once for every include. This template (based on existing test templates):

<pre>
<html>
<head>
<title>Hello [% name %]</title>
</head>
<body>
[% INCLUDE "included" %]
[% INCLUDE "included" %]
</body>
</html>
</pre>

Produces this output:

<pre>
return sub ($context) {
 my $stash = $context.stash;
my $output = '';
$output ~= Q{{{{<html>
<head>
<title>Hello }}}};
$output ~= $stash.get('name');$output ~= Q{{{{</title>
</head>
<body>}}}};
my %localdata;
{
 my $tfile = $stash.get('included');
my $template = $context.process($tfile, :localise, |%localdata);
if $template.defined { $output ~= $template; }
}
$output ~= Q{{{{}}}};
my %localdata;
{
 my $tfile = $stash.get('included');
my $template = $context.process($tfile, :localise, |%localdata);
if $template.defined { $output ~= $template; }
}
$output ~= Q{{{{
</body>
</html>
}}}};
return $output;
}
</pre>

I tried to write a unittest, but couldn't find out a way to find out if EVAL had produced any warnings

**Comment by 2colours** [comment]
For now, I'd close this issue. It has been fixed a long time ago, even if the solution is kinda superficial.
